-- =============================================================================
-- Migration 001: Add approval workflow columns to llm_feedback_draft
--
-- Sprint 3 — Status lifecycle: pending → approved → published
--   - pending:   Draft generated by LLM (TA review pending)
--   - approved:  TA reviewed and approved the feedback
--   - published: Instructor/Professor published the feedback to students
--
-- Usage (Colleague A):
--   psql agentic_ta -f db/migrations/add_draft_status.sql
--
-- Idempotent: safe to run multiple times (IF NOT EXISTS / EXCEPTION handler)
-- =============================================================================

BEGIN;

-- 1. Add status column (Add status column)
--    DEFAULT 'pending' ensures existing rows and new inserts without
--    explicit status are set to 'pending' automatically.
--    Existing rows and new inserts without explicit status are set to 'pending' automatically.
ALTER TABLE llm_feedback_draft
  ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'pending';

-- 2. Add approved_by column (Add approved_by column)
ALTER TABLE llm_feedback_draft
  ADD COLUMN IF NOT EXISTS approved_by UUID REFERENCES ta(ta_id);

-- 3. Add approved_at column (Add approved_at column)
ALTER TABLE llm_feedback_draft
  ADD COLUMN IF NOT EXISTS approved_at TIMESTAMPTZ;

-- 4. Add published_at column (Add published_at column)
ALTER TABLE llm_feedback_draft
  ADD COLUMN IF NOT EXISTS published_at TIMESTAMPTZ;

-- 5. CHECK constraint: status must be one of the three allowed values
--    Note: ADD CONSTRAINT IF NOT EXISTS requires PostgreSQL 15+.
--    For PostgreSQL 12-14 compatibility, use DO $$ EXCEPTION handler.
DO $$
BEGIN
  ALTER TABLE llm_feedback_draft
    ADD CONSTRAINT chk_draft_status
    CHECK (status IN ('pending', 'approved', 'published'));
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- 6. Composite index for common query: list drafts by submission + status
CREATE INDEX IF NOT EXISTS ix_llm_draft_submission_status
  ON llm_feedback_draft(submission_id, status);

COMMIT;
