"""Pydantic v2 models for seed data entities.

Defines the data models that mirror the database schema for the seed data
generation pipeline. Each model corresponds to a table/collection in the
Agentic TA system's database and is used to:

1. **Validate generated data** — Field validators enforce enum constraints,
   numeric ranges, and type correctness at creation time.
2. **Serialize to JSON/CSV** — Pydantic's built-in serialization is used
   to write metadata files (submissions.csv, artifacts.csv, etc.).
3. **Document the schema** — These models serve as the canonical reference
   for the data format expected by downstream systems (API, database).

Model hierarchy and relationships:
    Submission (1)
        |-- SubmissionArtifact (1:N)  — files attached to the submission
        |-- ExecutionResult (1:1)     — code execution outcome
        |       |-- TestCaseResult (1:N)  — per-test-case results
        |-- SubmissionTag (1:N)       — classification labels
        |-- SimilarityScore (1:N)     — plagiarism comparisons
        |-- Manifest (1:1)            — JSON manifest file
                |-- ManifestArtifact (1:N)  — artifact entries in manifest

All StrEnum validation is performed against enums defined in config.py,
ensuring that only valid categorical values are accepted.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from pydantic import BaseModel, Field, field_validator

from make_simul_data.seed_data.config import (
    ArtifactType,
    ExecutionStatus,
    SimilarityMethod,
    SubmissionStatus,
    TagSource,
    TagType,
)


class Submission(BaseModel):
    """A single student submission attempt for an assignment.

    This is the central entity in the seed data schema. Every other model
    references a Submission either directly (via submission_id FK) or
    indirectly (via ExecutionResult -> TestCaseResult).

    Created by: generate_data.py (main generation loop iterates over
                students x assignments x attempts)
    Referenced by: SubmissionArtifact, ExecutionResult, SubmissionTag,
                   SimilarityScore, Manifest
    Serialized to: metadata/submissions.csv

    Attributes:
        submission_id: Auto-generated UUID v4 primary key. Uniquely
                       identifies this submission across the entire dataset.
                       Other models use this as a foreign key.
        student_id:    Student identifier string (e.g., "S001").
                       Generated by students.py. Links this submission
                       to a specific simulated student.
        assignment_id: Assignment identifier string (e.g., "HW1").
                       Matches AssignmentDef.assignment_id from config.py.
                       Determines which rubric and test cases apply.
        attempt_no:    Which attempt this is (1, 2, or 3). Constrained
                       to [1, 3] by Field(ge=1, le=3). Later attempts
                       for the same student-assignment pair typically
                       have higher scores (improvement simulation).
        submitted_at:  UTC timestamp when the student submitted. Generated
                       relative to the assignment's due_at. If status is
                       "late", submitted_at > due_at.
        due_at:        UTC timestamp of the assignment deadline. Copied
                       from AssignmentDef.due_date for each submission.
        status:        Submission status string. Must be one of the values
                       in SubmissionStatus enum: "on_time", "late", or
                       "missing". Validated by validate_status().
    """

    submission_id: uuid.UUID = Field(default_factory=uuid.uuid4)
    student_id: str
    assignment_id: str
    attempt_no: int = Field(ge=1, le=3)
    submitted_at: datetime
    due_at: datetime
    status: str

    @field_validator("status")
    @classmethod
    def validate_status(cls, v: str) -> str:
        """Validate that status is a recognized SubmissionStatus value.

        Checks the input string against all values in the SubmissionStatus
        enum (defined in config.py). Raises ValueError with a descriptive
        message if the value is not valid, preventing invalid data from
        entering the pipeline.

        Args:
            v: The status string to validate.

        Returns:
            The validated status string (unchanged if valid).

        Raises:
            ValueError: If v is not in {"on_time", "late", "missing"}.
        """
        valid = {s.value for s in SubmissionStatus}
        if v not in valid:
            raise ValueError(f"Invalid status: {v!r}. Must be one of {valid}")
        return v


class SubmissionArtifact(BaseModel):
    """A file artifact attached to a submission.

    Each submission can have multiple artifacts (e.g., a Python file,
    a ZIP bundle, and a PDF report). This model tracks the metadata
    for each physical file in the submission.

    Created by: code_gen.py (python_file), zip_gen.py (zip_bundle),
                pdf_gen.py (pdf_report, ocr_image)
    Referenced by: ManifestArtifact (duplicates key fields for the manifest)
    Serialized to: metadata/artifacts.csv

    Attributes:
        artifact_id:   Auto-generated UUID v4 primary key. Uniquely
                       identifies this artifact file.
        submission_id: Foreign key to the parent Submission. Links this
                       artifact to the submission it belongs to.
        artifact_type: Type of artifact as a string. Must be one of the
                       values in ArtifactType enum: "python_file",
                       "zip_bundle", "pdf_report", or "ocr_image".
                       Validated by validate_artifact_type().
        filename:      Name of the artifact file on disk
                       (e.g., "main.py", "submission.zip", "report.pdf").
                       Does not include the directory path.
        filetype:      MIME type string describing the file format
                       (e.g., "text/x-python", "application/zip",
                       "application/pdf", "image/png").
        sha256:        SHA-256 hex digest (64 characters) of the file
                       contents. Used for integrity verification and
                       deduplication. Computed by hashlib.sha256().
        size_bytes:    File size in bytes. Must be >= 0. Generated within
                       the ranges defined in config.py (FILE_SIZE_PYTHON,
                       FILE_SIZE_ZIP, FILE_SIZE_PDF).
    """

    artifact_id: uuid.UUID = Field(default_factory=uuid.uuid4)
    submission_id: uuid.UUID
    artifact_type: str
    filename: str
    filetype: str
    sha256: str
    size_bytes: int = Field(ge=0)

    @field_validator("artifact_type")
    @classmethod
    def validate_artifact_type(cls, v: str) -> str:
        """Validate that artifact_type is a recognized ArtifactType value.

        Checks the input string against all values in the ArtifactType
        enum (defined in config.py). Raises ValueError with a descriptive
        message if the value is not valid.

        Args:
            v: The artifact_type string to validate.

        Returns:
            The validated artifact_type string (unchanged if valid).

        Raises:
            ValueError: If v is not in {"python_file", "zip_bundle",
                        "pdf_report", "ocr_image"}.
        """
        valid = {a.value for a in ArtifactType}
        if v not in valid:
            raise ValueError(f"Invalid artifact_type: {v!r}. Must be one of {valid}")
        return v


class ExecutionResult(BaseModel):
    """Result of executing a student's submitted code in the sandbox.

    Each submission has exactly one ExecutionResult, representing what
    happened when the student's code was run against the assignment's
    test cases. In the seed data pipeline, execution is *simulated*
    (no actual subprocess is spawned); outcomes are generated
    probabilistically based on student skill level and PASS_RATES.

    Created by: grading.py (simulates execution outcomes)
    Referenced by: TestCaseResult (via exec_id foreign key)
    Serialized to: metadata/execution_results.csv

    Attributes:
        exec_id:      Auto-generated UUID v4 primary key. Uniquely
                      identifies this execution run.
        submission_id: Foreign key to the parent Submission. Each
                      Submission has exactly one ExecutionResult.
        started_at:   UTC timestamp when execution began. In simulation,
                      set to submitted_at + small random offset.
        finished_at:  UTC timestamp when execution ended. Computed as
                      started_at + runtime_ms milliseconds.
        status:       Execution outcome string. Must be one of the values
                      in ExecutionStatus enum: "success", "runtime_error",
                      "timeout", or "compilation_error".
                      Validated by validate_status().
        exit_code:    Process exit code. 0 for success, non-zero for errors.
                      Typical values: 0 (success), 1 (runtime error),
                      -1 (timeout/killed), 2 (compilation error).
        stdout:       Captured standard output from the execution.
                      Contains test case output for successful runs.
                      May be empty for failed runs. Default: "".
        stderr:       Captured standard error from the execution.
                      Contains error messages and tracebacks for failed
                      runs. Empty for successful runs. Default: "".
        runtime_ms:   Total execution duration in milliseconds. Must be
                      >= 0. For successful runs, sampled from
                      [RUNTIME_MIN_MS, RUNTIME_MAX_MS]. For timeouts,
                      set to TIMEOUT_MS. For compilation errors, set to
                      a small value (code never actually ran).
    """

    exec_id: uuid.UUID = Field(default_factory=uuid.uuid4)
    submission_id: uuid.UUID
    started_at: datetime
    finished_at: datetime
    status: str
    exit_code: int
    stdout: str = ""
    stderr: str = ""
    runtime_ms: int = Field(ge=0)

    @field_validator("status")
    @classmethod
    def validate_status(cls, v: str) -> str:
        """Validate that status is a recognized ExecutionStatus value.

        Args:
            v: The execution status string to validate.

        Returns:
            The validated status string (unchanged if valid).

        Raises:
            ValueError: If v is not in {"success", "runtime_error",
                        "timeout", "compilation_error"}.
        """
        valid = {s.value for s in ExecutionStatus}
        if v not in valid:
            raise ValueError(f"Invalid status: {v!r}. Must be one of {valid}")
        return v


class TestCaseResult(BaseModel):
    """Result of running a single test case against student code.

    Each ExecutionResult has multiple TestCaseResults — one per test case
    defined in AssignmentDef.num_test_cases. For example, an assignment
    with 10 test cases produces 10 TestCaseResult records.

    Created by: grading.py (generates pass/fail per test case based on
                PASS_RATES and student skill level)
    Serialized to: metadata/test_case_results.csv

    Attributes:
        test_id:       Auto-generated UUID v4 primary key. Uniquely
                       identifies this test case execution.
        exec_id:       Foreign key to the parent ExecutionResult.
                       Links this test result to a specific execution run.
        test_case_id:  Test case identifier string (e.g., "HW1_TC01",
                       "HW1_TC02"). Format: "{assignment_id}_TC{number:02d}".
                       Defined per assignment in assignments.py.
        passed:        Boolean indicating whether the test case passed.
                       True if the student's output matched the expected
                       output; False otherwise.
        score_awarded: Points awarded for this test case. Must be >= 0.
                       Equals max_points_per_test if passed, 0 if failed,
                       or a partial value for partial-credit scenarios.
                       Computed as: assignment.max_score / num_test_cases
                       (evenly distributed across test cases).
        output:        Captured output specific to this test case.
                       Contains the actual vs expected comparison or
                       error details. Default: "".
    """

    test_id: uuid.UUID = Field(default_factory=uuid.uuid4)
    exec_id: uuid.UUID
    test_case_id: str
    passed: bool
    score_awarded: float = Field(ge=0.0)
    output: str = ""


class SubmissionTag(BaseModel):
    """A classification tag applied to a submission for filtering and triage.

    Tags categorize submissions for the Agentic TA's automated workflow.
    A single submission can have multiple tags (e.g., both "late_submission"
    and "clean"). Tags are used by the UI to display status badges and
    by analytics to compute class-wide distributions.

    Created by: generate_data.py (assigns tags based on submission
                properties — e.g., late submissions get "late_submission",
                high-similarity pairs get "plagiarism_suspect")
    Serialized to: metadata/tags.csv

    Note: This model has no auto-generated primary key because the
    (submission_id, tag) pair serves as a natural composite key.

    Attributes:
        submission_id: Foreign key to the tagged Submission. A submission
                       can have multiple tags (one SubmissionTag record
                       per tag).
        tag:           Tag type string. Must be one of the values in
                       TagType enum: "clean", "plagiarism_suspect",
                       "corrupted", "late_submission", or "excellent".
                       Validated by validate_tag().
        source:        How the tag was assigned. Must be one of the values
                       in TagSource enum: "automated" (assigned by the
                       pipeline) or "manual" (assigned by a human TA).
                       In simulated data, all tags use "automated".
                       Validated by validate_source().
        confidence:    Confidence score for the tag assignment, ranging
                       from 0.0 (no confidence) to 1.0 (fully confident).
                       For automated tags, this reflects the algorithm's
                       certainty. For manual tags, typically set to 1.0.
    """

    submission_id: uuid.UUID
    tag: str
    source: str
    confidence: float = Field(ge=0.0, le=1.0)

    @field_validator("tag")
    @classmethod
    def validate_tag(cls, v: str) -> str:
        """Validate that tag is a recognized TagType value.

        Args:
            v: The tag string to validate.

        Returns:
            The validated tag string (unchanged if valid).

        Raises:
            ValueError: If v is not in {"clean", "plagiarism_suspect",
                        "corrupted", "late_submission", "excellent"}.
        """
        valid = {t.value for t in TagType}
        if v not in valid:
            raise ValueError(f"Invalid tag: {v!r}. Must be one of {valid}")
        return v

    @field_validator("source")
    @classmethod
    def validate_source(cls, v: str) -> str:
        """Validate that source is a recognized TagSource value.

        Args:
            v: The source string to validate.

        Returns:
            The validated source string (unchanged if valid).

        Raises:
            ValueError: If v is not in {"automated", "manual"}.
        """
        valid = {s.value for s in TagSource}
        if v not in valid:
            raise ValueError(f"Invalid source: {v!r}. Must be one of {valid}")
        return v


class SimilarityScore(BaseModel):
    """Plagiarism similarity comparison between two submissions.

    Records the result of comparing one submission against another using
    a specific similarity algorithm. These pairwise comparisons are used
    by the Agentic TA system to flag potential plagiarism cases.

    For N submissions within the same assignment, up to N*(N-1)/2 pairwise
    comparisons can be generated. In practice, only a subset is sampled
    to keep the dataset size manageable.

    Created by: plagiarism.py (generates pairwise similarity scores
                using rapidfuzz for text-based comparison, AST-based
                structural comparison, and token-based comparison)
    Serialized to: metadata/similarity_scores.csv

    Attributes:
        sim_id:          Auto-generated UUID v4 primary key. Uniquely
                         identifies this similarity comparison.
        submission_id:   Foreign key to the first (source) submission
                         in the comparison pair.
        compared_to:     Foreign key (UUID) to the second (target)
                         submission being compared against. Together with
                         submission_id, forms a directed pair.
        method:          Similarity algorithm used. Must be one of the
                         values in SimilarityMethod enum: "token_based",
                         "ast_based", or "text_based".
                         Validated by validate_method().
        similarity_pct:  Similarity percentage from 0.0 to 100.0.
                         Higher values indicate more similar code.
                         The flagging threshold is typically 80%.
        flagged:         Boolean indicating whether this pair exceeds
                         the plagiarism threshold and requires manual
                         review. Default: False. Set to True when
                         similarity_pct > threshold (configured per
                         assignment or globally).
    """

    sim_id: uuid.UUID = Field(default_factory=uuid.uuid4)
    submission_id: uuid.UUID
    compared_to: uuid.UUID
    method: str
    similarity_pct: float = Field(ge=0.0, le=100.0)
    flagged: bool = False

    @field_validator("method")
    @classmethod
    def validate_method(cls, v: str) -> str:
        """Validate that method is a recognized SimilarityMethod value.

        Args:
            v: The similarity method string to validate.

        Returns:
            The validated method string (unchanged if valid).

        Raises:
            ValueError: If v is not in {"token_based", "ast_based",
                        "text_based"}.
        """
        valid = {m.value for m in SimilarityMethod}
        if v not in valid:
            raise ValueError(f"Invalid method: {v!r}. Must be one of {valid}")
        return v


class ManifestArtifact(BaseModel):
    """A single artifact entry within a submission manifest.

    This is a lightweight summary of a SubmissionArtifact, containing
    only the fields needed for the manifest.json file. It omits the
    artifact_id and submission_id since those are implicit from the
    parent Manifest.

    Created by: manifest.py (extracts key fields from SubmissionArtifact
                records to build the manifest's artifact list)

    Attributes:
        filename:      Name of the artifact file (e.g., "main.py").
                       Matches SubmissionArtifact.filename.
        artifact_type: Type of artifact (e.g., "python_file").
                       Matches SubmissionArtifact.artifact_type.
        sha256:        SHA-256 hex digest of the file contents.
                       Used for integrity verification when consuming
                       the manifest. Matches SubmissionArtifact.sha256.
        size_bytes:    File size in bytes. Matches
                       SubmissionArtifact.size_bytes.
    """

    filename: str
    artifact_type: str
    sha256: str
    size_bytes: int


class Manifest(BaseModel):
    """Per-submission manifest.json schema.

    Each submission gets a manifest.json file written alongside its
    artifact files (inside the submission's directory). The manifest
    serves as a machine-readable index of the submission's contents,
    enabling downstream systems to discover and validate artifacts
    without scanning the file system.

    The manifest is the final output of the generation pipeline for
    each submission, created after all artifacts have been generated.

    Created by: manifest.py (assembles manifest from Submission and
                SubmissionArtifact records)
    Written to: ASSIGNMENTS_DIR / {assignment_id} / {student_id}_attempt{n}
                / manifest.json
    Validated by: jsonschema (Step 9 validation checks manifest structure)

    Attributes:
        submission_id: UUID of the parent Submission. Used to cross-reference
                       with the metadata CSV files.
        student_id:    Student identifier string (e.g., "S001"). Duplicated
                       from Submission for convenient access without
                       joining tables.
        assignment_id: Assignment identifier string (e.g., "HW1"). Duplicated
                       from Submission for the same reason.
        attempt_no:    Attempt number (1, 2, or 3). Duplicated from
                       Submission for directory naming and lookup.
        generated_at:  UTC timestamp when this manifest was generated.
                       Allows tracking when the seed data was produced.
        artifacts:     List of ManifestArtifact entries describing each
                       file in this submission. Default: empty list.
                       Populated by manifest.py from the submission's
                       SubmissionArtifact records.
    """

    submission_id: uuid.UUID
    student_id: str
    assignment_id: str
    attempt_no: int
    generated_at: datetime
    artifacts: list[ManifestArtifact] = Field(default_factory=list)
