"""Student profile generation for the seed data pipeline.

This module generates simulated student profiles for a CS1 (Intro to CS)
course. Each student has a unique ID, fake name/email (via Faker), a
skill level drawn from a Beta distribution, pre-computed attempt counts
per assignment, and behavioral flags (late submitter, generates PDF).

StudentProfile is a frozen dataclass (not a Pydantic model) because it
is an internal pipeline configuration struct — not a database-facing entity.
This design mirrors AssignmentDef and SeedDataConfig in config.py.

Module dependency graph:
    config.py  -->  students.py  (imports NUM_STUDENTS, SCORE_ALPHA,
                                  SCORE_BETA, LATE_RATE, PDF_GENERATION_RATE,
                                  SUBMISSION_DISTRIBUTION, NUM_ASSIGNMENTS,
                                  create_rng)

Consumed by:
    generate_data.py  (iterates over students in the main loop)
    code_generator.py (uses skill_level to vary code quality)
    grading_engine.py (uses skill_level for score distribution)
"""

from __future__ import annotations

import random
from dataclasses import dataclass

from faker import Faker

from make_simul_data.seed_data.config import (
    LATE_RATE,
    MASTER_SEED,
    NUM_ASSIGNMENTS,
    NUM_STUDENTS,
    PDF_GENERATION_RATE,
    SCORE_ALPHA,
    SCORE_BETA,
    SUBMISSION_DISTRIBUTION,
    create_rng,
)

# ── Data Structures ─────────────────────────────────────────────────────


@dataclass(frozen=True)
class StudentProfile:
    """Immutable profile of a single simulated student.

    Each StudentProfile represents one student in the CS1 course with
    deterministic attributes generated from a seed. The profile contains
    both identity fields (name, email) and behavioral parameters
    (skill_level, attempt_counts) that drive downstream generation.

    Created by: generate_students() in this module.
    Consumed by: generate_data.py (main loop), code_generator.py (code
                 quality), grading_engine.py (score distribution).

    Attributes:
        student_id:        Unique identifier string in "S{NNN}" format
                           (e.g., "S001", "S042", "S100"). Zero-padded
                           to 3 digits. Used as a foreign key in
                           Submission records and directory naming.
        name:              Full name generated by Faker (e.g., "John Smith").
                           Used in PDF report headers and metadata CSV.
        email:             Email address generated by Faker
                           (e.g., "jsmith@example.com"). Unique per student.
                           Used in metadata CSV for student records.
        skill_level:       Float in [0.0, 1.0] drawn from Beta(SCORE_ALPHA,
                           SCORE_BETA) distribution. Higher values indicate
                           stronger programming skills. Influences:
                           - Code quality in code_generator.py
                           - Score distribution in grading_engine.py
                           - Test case pass rates
        attempt_counts:    Pre-computed attempt counts per assignment, stored
                           as an immutable tuple of (assignment_id, count)
                           pairs. Example: (("HW1", 1), ("HW2", 2), ...).
                           Counts are sampled from SUBMISSION_DISTRIBUTION
                           {1: 0.60, 2: 0.30, 3: 0.10} at generation time.
                           Use get_attempt_count() to look up a specific
                           assignment's count conveniently.
        is_late_submitter: Whether this student tends to submit late.
                           True for ~LATE_RATE (20%) of students. When True,
                           this student's submissions are candidates for
                           late status (actual late marking is further
                           randomized in generate_data.py).
        generates_pdf:     Whether this student submits PDF lab reports.
                           True for ~PDF_GENERATION_RATE (40%) of students.
                           Controls whether report_generator.py creates a
                           PDF artifact for this student's submissions.
    """

    student_id: str
    name: str
    email: str
    skill_level: float
    attempt_counts: tuple[tuple[str, int], ...]
    is_late_submitter: bool
    generates_pdf: bool


# ── Helper Functions ────────────────────────────────────────────────────


def get_attempt_count(student: StudentProfile, assignment_id: str) -> int:
    """Retrieve the pre-computed attempt count for a specific assignment.

    Looks up the attempt count from the student's attempt_counts tuple
    for the given assignment_id. This is a convenience function that
    avoids manual tuple traversal in downstream modules.

    Used by: generate_data.py (to determine how many submission attempts
             to generate for each student-assignment pair)

    Args:
        student: The StudentProfile to query.
        assignment_id: Assignment identifier (e.g., "HW1").

    Returns:
        The number of attempts (1, 2, or 3) for this student-assignment
        pair.

    Raises:
        KeyError: If assignment_id is not found in the student's
                  attempt_counts tuple.

    Example::

        student = generate_students(num=1, seed=42)[0]
        count = get_attempt_count(student, "HW1")  # e.g., 1
    """
    for aid, count in student.attempt_counts:
        if aid == assignment_id:
            return count
    raise KeyError(
        f"Assignment {assignment_id!r} not found in attempt_counts "
        f"for student {student.student_id}"
    )


# ── Main Generation Function ───────────────────────────────────────────


def generate_students(
    num: int = NUM_STUDENTS,
    seed: int | None = None,
    num_assignments: int = NUM_ASSIGNMENTS,
) -> list[StudentProfile]:
    """Generate a list of simulated student profiles with deterministic attributes.

    Creates ``num`` StudentProfile instances with fake identities (via Faker),
    Beta-distributed skill levels, pre-computed attempt counts, and
    behavioral flags. All randomness is controlled by the provided seed
    for full reproducibility.

    The generation process for each student:
        1. Generate student_id as "S{i:03d}" (e.g., "S001").
        2. Generate name and email via Faker (seeded for determinism).
        3. Sample skill_level from Beta(SCORE_ALPHA, SCORE_BETA).
        4. Sample attempt_counts for each assignment from
           SUBMISSION_DISTRIBUTION via rng.choices().
        5. Determine is_late_submitter (True with probability LATE_RATE).
        6. Determine generates_pdf (True with probability PDF_GENERATION_RATE).

    Used by: generate_data.py (called once at pipeline start to create
             the full student roster)

    Args:
        num: Number of students to generate. Default: NUM_STUDENTS (100).
        seed: Random seed for reproducibility. Default: None (uses
              MASTER_SEED via create_rng).
        num_assignments: Number of assignments for pre-computing
                         attempt_counts. Default: NUM_ASSIGNMENTS (5).

    Returns:
        A list of ``num`` StudentProfile instances, ordered by student_id
        (S001, S002, ..., S{num}).

    Example::

        students = generate_students(num=10, seed=42)
        assert len(students) == 10
        assert students[0].student_id == "S001"
    """
    # Create an isolated Random instance for reproducibility.
    # This RNG drives all random decisions (skill_level, attempt counts,
    # behavioral flags) and is independent of the global random state.
    rng: random.Random = create_rng(seed)

    # Create a dedicated Faker instance with instance-level seeding.
    # Using seed_instance() (not the global Faker.seed()) avoids
    # contaminating other Faker instances in the pipeline.
    fake = Faker()
    fake.seed_instance(seed if seed is not None else MASTER_SEED)

    # Pre-extract the attempt count values and weights from
    # SUBMISSION_DISTRIBUTION for use with rng.choices().
    # SUBMISSION_DISTRIBUTION = {1: 0.60, 2: 0.30, 3: 0.10}
    attempt_values: list[int] = list(SUBMISSION_DISTRIBUTION.keys())
    attempt_weights: list[float] = list(SUBMISSION_DISTRIBUTION.values())

    # Track seen emails to guarantee uniqueness across all students.
    seen_emails: set[str] = set()

    students: list[StudentProfile] = []

    for i in range(1, num + 1):
        # Student ID: zero-padded 3-digit format (e.g., "S001", "S100").
        # Used as a foreign key in Submission records and as directory
        # names in the output file structure.
        student_id = f"S{i:03d}"

        # Full name from Faker (e.g., "John Smith", "Maria Garcia").
        # Deterministic due to seed_instance() call above.
        name: str = fake.name()

        # Unique email from Faker (e.g., "jsmith@example.com").
        # Retry on collision to guarantee uniqueness across all students.
        email: str = fake.email()
        while email in seen_emails:
            email = fake.email()
        seen_emails.add(email)

        # Skill level from Beta(5, 2) distribution, range [0.0, 1.0].
        # Beta(5, 2) is left-skewed with mean ~0.714, meaning most
        # students have above-average skills — consistent with a
        # self-selected CS1 population at a university.
        # Higher skill_level -> better code quality, higher scores.
        skill_level: float = rng.betavariate(SCORE_ALPHA, SCORE_BETA)

        # Pre-compute attempt counts for each assignment (HW1..HW{n}).
        # Using rng.choices() with SUBMISSION_DISTRIBUTION weights:
        #   60% chance of 1 attempt, 30% of 2, 10% of 3.
        # Pre-computation at generation time ensures reproducibility
        # regardless of the order assignments are processed later.
        attempt_counts_list: list[tuple[str, int]] = []
        for j in range(1, num_assignments + 1):
            assignment_id = f"HW{j}"
            count: int = rng.choices(attempt_values, weights=attempt_weights, k=1)[0]
            attempt_counts_list.append((assignment_id, count))

        # Late submitter flag: True with probability LATE_RATE (0.20).
        # When True, this student's submissions are candidates for
        # "late" status. The actual late marking is further randomized
        # per submission in generate_data.py.
        is_late_submitter: bool = rng.random() < LATE_RATE

        # PDF generation flag: True with probability PDF_GENERATION_RATE (0.40).
        # When True, report_generator.py will create a PDF write-up
        # artifact for this student's submissions.
        generates_pdf: bool = rng.random() < PDF_GENERATION_RATE

        student = StudentProfile(
            student_id=student_id,
            name=name,
            email=email,
            skill_level=skill_level,
            attempt_counts=tuple(attempt_counts_list),
            is_late_submitter=is_late_submitter,
            generates_pdf=generates_pdf,
        )
        students.append(student)

    return students
